version: "3.9"
services:
  skilllease-api:
    build: ./
    ports:
      - "8080:8080"
    container_name: skilllease_api
    networks:
      - skilllease-net

  postgres:
    image: postgres:16.6
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: skilllease-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - skilllease-net

volumes:
  postgres_data:
networks:
  skilllease-net:
    driver: bridge