version: "3.9"
services:
  skilllease-api:
    build: ./
    ports:
      - "8080:8080"
    container_name: skilllease_api
#    environment:
#      - DB_HOST=<DB_HOST>
#      - DB_NAME=<DB_NAME>
#      - DB_USER=<DB_USER>
#      - DB_PASS=<DB_PASS>
    networks:
      - skilllease-net

networks:
  skilllease-net:
    driver: bridge